name: launch_pad
description: "🎵 Launch Pad Music App Dive into a musical journey with pads that play unique sounds. Crafted by Sagnik Bhattacharya from Coding Liquids for the course Complete Flutter Guide Build Android, iOS, and Web. An interactive way to learn Flutter!"


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <7.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  audioplayers: ^6.0.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

  flutter_app_name: ^0.1.1
flutter_app_name:
  name: "LaunchPad"

flutter:


  uses-material-design: true


  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

